version: '3.1'
services:
  discount-service:
    image: betulcetinkaya/discount-service:${TAG}
    container_name: discount-service
    env_file: docker-compose.env
    ports:
      - 8083:8083
    networks:
        - services
networks:
  services:
    external:
      name: services
